# Generated by Django 5.1.4 on 2025-01-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name="SEO Ta'rifi")),
                ('name', models.CharField(max_length=100, verbose_name='Muallif ismi')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name="SEO Ta'rifi")),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Rasm')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.author', verbose_name='Muallif')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
